tap 'shopify/shopify'

brew "asdf"
brew "coreutils"
brew "curl"
brew "gawk"
brew "git"
brew "gpg"
brew "peco"
brew "stow"
brew "starship"
brew "themekit"
brew "zsh-autosuggestions"

cask "alacritty"
cask "android-studio"
cask "cursor"
cask "docker"
cask "google-chrome"
cask "slack"
cask "visual-studio-code"
