#!/bin/sh

set -e

if [ ! -f /opt/homebrew/bin/brew ]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
     (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/yfurusawa/.zprofile
     eval "$(/opt/homebrew/bin/brew shellenv)"
fi

if [ ! -d ~/dotfiles ]; then
    cd ~
    git clone git https://github.com/YFurusawa727/dotfiles.git
fi

brew bundle -v --file=~/dotfiles/Brewfile

if [ ! -d ~/.config ]; then
    mkdir ~/.config/
fi

stow -v -d ~/dotfiles/packages -t ~ zsh starship alacritty