live_config_reload = true

[window]
dynamic_title = true
opacity = 0.87

[window.dimensions]
columns = 150
lines = 40

[window.padding]
x = 5
y = 0

[cursor]
blink_interval = 400
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Block"

[scrolling]
history = 10000

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.glyph_offset]
x = 0
y = 0

[font.normal]
# family = "FiraCode Nerd Font"
# family = "JetBrainsMono Nerd Font"

[font.offset]
x = 0
y = 0