alias a='alias'
alias ..='cd ..'
alias ..2='cd ../..'
alias ..3='cd ../../..'
alias ll='clear && ls -alF --color=auto'
alias m='make'
alias yakata='cd ~/dev/yakata-online'
alias dotinstall='~/dotfiles/install'