alias a='alias'
alias ..='cd ..'
alias ..2='cd ../..'
alias ..3='cd ../../..'
alias ll='clear && ls -alF --color=auto'
alias g='git'
alias m='make'
alias s='ssh'
alias dotinstall='~/dotfiles/install'
alias page='~/dotfiles/page_display'